# -*- coding: utf-8 -*-
"""SCT_DS_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Doy32F_myj75Lmx5voM04RIUpbUVO9kO
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Paste the path you copied in the previous step
file_path = '/content/drive/MyDrive/US_Accidents_March23.csv'

try:
    # Load the data
    df = pd.read_csv(file_path, nrows=10000)
    print(df.head())

    # Display the first 5 rows to confirm it worked
    print("\n--- First 5 Rows of the Dataset ---")
    print(df.head())

    # Display info to see the columns and data types
    print("\n--- Data Info ---")
    df_sample.info()

except FileNotFoundError:
    print(f"❌ Error: File not found at the path '{file_path}'. Please double-check the path you copied.")

"""***Analyze the Target Variable (Severity)***"""

# Check the distribution of the 'Severity' column
print("--- Severity Distribution ---")
severity_counts = df['Severity'].value_counts().sort_index()
print(severity_counts)

# Visualize the Severity distribution
plt.figure(figsize=(8, 6))
sns.countplot(x='Severity', data=df, palette='viridis')
plt.title('Distribution of Accident Severity (1=Low, 4=High)', fontsize=16)
plt.xlabel('Severity Level')
plt.ylabel('Number of Accidents')
plt.show()

"""***Explore Key Features***"""

# Convert Start_Time to a proper datetime format for analysis
df_sample['Start_Time'] = pd.to_datetime(df_sample['Start_Time'])

# Extract the hour of the day
df_sample['Hour'] = df_sample['Start_Time'].dt.hour

# Visualize accidents by hour of the day
plt.figure(figsize=(12, 6))
sns.countplot(x='Hour', data=df_sample, palette='magma')
plt.title('Number of Accidents by Hour of the Day', fontsize=16)
plt.xlabel('Hour (24-hour format)')
plt.ylabel('Number of Accidents')
plt.show()

# Extract the day of the week (Monday=0, Sunday=6)
df_sample['DayOfWeek'] = df_sample['Start_Time'].dt.dayofweek

# Visualize accidents by day of the week
plt.figure(figsize=(10, 6))
sns.countplot(x='DayOfWeek', data=df_sample, palette='plasma')
plt.title('Number of Accidents by Day of the Week', fontsize=16)
plt.xlabel('Day of the Week')
plt.ylabel('Number of Accidents')
plt.xticks(ticks=[0, 1, 2, 3, 4, 5, 6], labels=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])
plt.show()

# Get the top 15 states with the most accidents
top_states = df['State'].value_counts().nlargest(15)

print("--- Top 15 States with Most Accidents ---")
print(top_states)

# Visualize the top 15 states
plt.figure(figsize=(12, 8))
sns.barplot(y=top_states.index, x=top_states.values, palette='cubehelix')
plt.title('Top 15 States by Number of Accidents', fontsize=16)
plt.xlabel('Number of Accidents')
plt.ylabel('State')
plt.show()

# Get the top 15 most common weather conditions
top_weather = df_sample['Weather_Condition'].value_counts().nlargest(15)

print("\n--- Top 15 Weather Conditions in Accidents ---")
print(top_weather)

# Visualize the top 15 weather conditions
plt.figure(figsize=(10, 8))
sns.barplot(y=top_weather.index, x=top_weather.values, palette='mako')
plt.title('Top 15 Weather Conditions During Accidents', fontsize=16)
plt.xlabel('Number of Accidents')
plt.ylabel('Weather Condition')
plt.show()

